create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  attending text not null check (attending in ('yes', 'no')),
  guests integer not null default 1 check (guests between 1 and 6),
  message text
);

alter table public.rsvps enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on public.rsvps to anon, authenticated;

drop policy if exists "Guests can submit rsvps" on public.rsvps;
create policy "Guests can submit rsvps"
on public.rsvps
for insert
to anon
with check (true);

insert into storage.buckets (id, name, public)
values ('wedding-photos', 'wedding-photos', false)
on conflict (id) do nothing;

drop policy if exists "Guests can upload wedding photos" on storage.objects;
create policy "Guests can upload wedding photos"
on storage.objects
for insert
to anon
with check (bucket_id = 'wedding-photos');
